-- +goose Up
CREATE TABLE IF NOT EXISTS menu(
	menu_id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	price REAL NOT NULL,
	type TEXT NOT NULL
);

ALTER TABLE menu
RENAME COLUMN type to menu_type;

ALTER TABLE menu
ADD COLUMN type TEXT;
