// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bill.sql

package database

import (
	"context"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bill(bill_id, pay_date)
VALUES (lower(hex(randomblob(8))), ?)
RETURNING bill_id, total, pay_date, user_id, giveaway_id
`

func (q *Queries) CreateBill(ctx context.Context, payDate string) (Bill, error) {
	row := q.db.QueryRowContext(ctx, createBill, payDate)
	var i Bill
	err := row.Scan(
		&i.BillID,
		&i.Total,
		&i.PayDate,
		&i.UserID,
		&i.GiveawayID,
	)
	return i, err
}

const deleteBill = `-- name: DeleteBill :exec
DELETE FROM bill
`

func (q *Queries) DeleteBill(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteBill)
	return err
}

const listBill = `-- name: ListBill :many
SELECT bill_id, total, pay_date, user_id, giveaway_id FROM bill
`

func (q *Queries) ListBill(ctx context.Context) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listBill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.BillID,
			&i.Total,
			&i.PayDate,
			&i.UserID,
			&i.GiveawayID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBillTotal = `-- name: UpdateBillTotal :one
UPDATE bill
SET total = ?
WHERE bill_id = ?
RETURNING bill_id, total, pay_date, user_id, giveaway_id
`

type UpdateBillTotalParams struct {
	Total  float64
	BillID string
}

func (q *Queries) UpdateBillTotal(ctx context.Context, arg UpdateBillTotalParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, updateBillTotal, arg.Total, arg.BillID)
	var i Bill
	err := row.Scan(
		&i.BillID,
		&i.Total,
		&i.PayDate,
		&i.UserID,
		&i.GiveawayID,
	)
	return i, err
}
