// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: menu.sql

package database

import (
	"context"
)

const addMenu = `-- name: AddMenu :exec
INSERT INTO menu(name,price,type) 
VALUES(?,?,?)
`

type AddMenuParams struct {
	Name  string
	Price float64
	Type  string
}

func (q *Queries) AddMenu(ctx context.Context, arg AddMenuParams) error {
	_, err := q.db.ExecContext(ctx, addMenu, arg.Name, arg.Price, arg.Type)
	return err
}

const deleteAllMenu = `-- name: DeleteAllMenu :exec
DELETE FROM menu
`

func (q *Queries) DeleteAllMenu(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMenu)
	return err
}

const deleteMenuByID = `-- name: DeleteMenuByID :exec
DELETE FROM menu
WHERE menu_id = ?
`

func (q *Queries) DeleteMenuByID(ctx context.Context, menuID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMenuByID, menuID)
	return err
}

const deleteMenuByName = `-- name: DeleteMenuByName :exec
DELETE FROM menu
WHERE name = ?
`

func (q *Queries) DeleteMenuByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteMenuByName, name)
	return err
}

const getAllMenus = `-- name: GetAllMenus :many
SELECT menu_id, name, price, type FROM menu
`

func (q *Queries) GetAllMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.QueryContext(ctx, getAllMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.MenuID,
			&i.Name,
			&i.Price,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllType = `-- name: GetAllType :many
SELECT type FROM menu
`

func (q *Queries) GetAllType(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenu = `-- name: GetMenu :one
SELECT menu_id, name, price, type FROM menu
WHERE name = ?
`

func (q *Queries) GetMenu(ctx context.Context, name string) (Menu, error) {
	row := q.db.QueryRowContext(ctx, getMenu, name)
	var i Menu
	err := row.Scan(
		&i.MenuID,
		&i.Name,
		&i.Price,
		&i.Type,
	)
	return i, err
}
