// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type User struct {
	UserID   interface{}
	Fname    sql.NullString
	Lname    sql.NullString
	Email    string
	Password string
}
