// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Gallery struct {
	Gname     string
	Startdate string
	Enddate   string
	Desc      sql.NullString
	UserID    interface{}
}

type GiveAway struct {
	ID     int64
	Name   string
	Amount int64
	Remain int64
	Desc   sql.NullString
	Date   time.Time
}

type Menu struct {
	MenuID   int64
	Name     string
	Price    float64
	MenuType string
	Type     string
}

type User struct {
	UserID   interface{}
	Fname    sql.NullString
	Lname    sql.NullString
	Email    string
	Password string
}
