// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order.sql

package database

import (
	"context"
)

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM "order"
`

func (q *Queries) DeleteOrder(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrder)
	return err
}
