// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bill.sql

package database

import (
	"context"
	"database/sql"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bill(bill_id, created_at, total)
VALUES (lower(hex(randomblob(8))), ?, 0)
RETURNING bill_id
`

func (q *Queries) CreateBill(ctx context.Context, createdAt string) (string, error) {
	row := q.db.QueryRowContext(ctx, createBill, createdAt)
	var bill_id string
	err := row.Scan(&bill_id)
	return bill_id, err
}

const deleteBill = `-- name: DeleteBill :exec
DELETE FROM bill
`

func (q *Queries) DeleteBill(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteBill)
	return err
}

const deleteBillByID = `-- name: DeleteBillByID :exec
DELETE FROM bill
WHERE bill_id = ?
`

func (q *Queries) DeleteBillByID(ctx context.Context, billID string) error {
	_, err := q.db.ExecContext(ctx, deleteBillByID, billID)
	return err
}

const getBillByID = `-- name: GetBillByID :one
SELECT bill_id, total, created_at, payment_method FROM bill
WHERE bill_id = ?
`

func (q *Queries) GetBillByID(ctx context.Context, billID string) (Bill, error) {
	row := q.db.QueryRowContext(ctx, getBillByID, billID)
	var i Bill
	err := row.Scan(
		&i.BillID,
		&i.Total,
		&i.CreatedAt,
		&i.PaymentMethod,
	)
	return i, err
}

const listBill = `-- name: ListBill :many
SELECT bill_id, total, created_at, payment_method FROM bill
`

func (q *Queries) ListBill(ctx context.Context) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listBill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.BillID,
			&i.Total,
			&i.CreatedAt,
			&i.PaymentMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBill = `-- name: UpdateBill :exec
UPDATE bill
SET total = ?, payment_method = ?
WHERE bill_id = ?
`

type UpdateBillParams struct {
	Total         float64
	PaymentMethod sql.NullString
	BillID        string
}

func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) error {
	_, err := q.db.ExecContext(ctx, updateBill, arg.Total, arg.PaymentMethod, arg.BillID)
	return err
}
