// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package database

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO "category"(menu_id,size,price)
VALUES(?, ?, ?)
`

type CreateCategoryParams struct {
	MenuID int64
	Size   sql.NullString
	Price  float64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory, arg.MenuID, arg.Size, arg.Price)
	return err
}

const deleteAllCategory = `-- name: DeleteAllCategory :exec
DELETE FROM "category"
`

func (q *Queries) DeleteAllCategory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCategory)
	return err
}

const deleteCategoryByMenuID = `-- name: DeleteCategoryByMenuID :exec
DELETE FROM "category"
where menu_id = ?
`

func (q *Queries) DeleteCategoryByMenuID(ctx context.Context, menuID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryByMenuID, menuID)
	return err
}

const getCategoryByMenuID = `-- name: GetCategoryByMenuID :many
SELECT menu_id, size, price FROM "category"
WHERE menu_id = ?
`

func (q *Queries) GetCategoryByMenuID(ctx context.Context, menuID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryByMenuID, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.MenuID, &i.Size, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
