// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu.sql

package database

import (
	"context"
	"database/sql"
)

const addMenu = `-- name: AddMenu :one
INSERT INTO menu(name, menu_type,img_url) 
VALUES(?, ?, ?)
RETURNING menu_id, name, menu_type, img_url, type
`

type AddMenuParams struct {
	Name     string
	MenuType string
	ImgUrl   sql.NullString
}

func (q *Queries) AddMenu(ctx context.Context, arg AddMenuParams) (Menu, error) {
	row := q.db.QueryRowContext(ctx, addMenu, arg.Name, arg.MenuType, arg.ImgUrl)
	var i Menu
	err := row.Scan(
		&i.MenuID,
		&i.Name,
		&i.MenuType,
		&i.ImgUrl,
		&i.Type,
	)
	return i, err
}

const deleteAllMenu = `-- name: DeleteAllMenu :exec
DELETE FROM menu
`

func (q *Queries) DeleteAllMenu(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllMenu)
	return err
}

const deleteMenuByID = `-- name: DeleteMenuByID :exec
DELETE FROM menu
WHERE menu_id = ?
`

func (q *Queries) DeleteMenuByID(ctx context.Context, menuID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMenuByID, menuID)
	return err
}

const getAllMenus = `-- name: GetAllMenus :many
SELECT menu_id, name, menu_type, img_url, type FROM menu
`

func (q *Queries) GetAllMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.QueryContext(ctx, getAllMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.MenuID,
			&i.Name,
			&i.MenuType,
			&i.ImgUrl,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenuByID = `-- name: GetMenuByID :one
SELECT menu_id, name, menu_type, img_url, type FROM menu
WHERE menu_id = ?
`

func (q *Queries) GetMenuByID(ctx context.Context, menuID int64) (Menu, error) {
	row := q.db.QueryRowContext(ctx, getMenuByID, menuID)
	var i Menu
	err := row.Scan(
		&i.MenuID,
		&i.Name,
		&i.MenuType,
		&i.ImgUrl,
		&i.Type,
	)
	return i, err
}

const updateMenuByID = `-- name: UpdateMenuByID :one
UPDATE menu
SET name = ?, menu_type = ? , img_url = ?
WHERE menu_id = ?
RETURNING menu_id, name, menu_type, img_url, type
`

type UpdateMenuByIDParams struct {
	Name     string
	MenuType string
	ImgUrl   sql.NullString
	MenuID   int64
}

func (q *Queries) UpdateMenuByID(ctx context.Context, arg UpdateMenuByIDParams) (Menu, error) {
	row := q.db.QueryRowContext(ctx, updateMenuByID,
		arg.Name,
		arg.MenuType,
		arg.ImgUrl,
		arg.MenuID,
	)
	var i Menu
	err := row.Scan(
		&i.MenuID,
		&i.Name,
		&i.MenuType,
		&i.ImgUrl,
		&i.Type,
	)
	return i, err
}
