// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Bill struct {
	BillID        string
	CreatedAt     string
	PaymentMethod sql.NullString
}

type Category struct {
	MenuID int64
	Size   sql.NullString
	Price  float64
}

type Menu struct {
	MenuID   int64
	Name     string
	MenuType string
	ImgUrl   sql.NullString
}

type Order struct {
	OrderID  int64
	BillID   string
	MenuID   int64
	Amount   int64
	Size     sql.NullString
	Type     sql.NullString
	MenuName string
}

type Type struct {
	MenuID        int64
	Type          sql.NullString
	AdditionPrice float64
}

type User struct {
	UserID   interface{}
	Fname    sql.NullString
	Lname    sql.NullString
	Email    string
	Password string
	Role     sql.NullString
}
