// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"
	"database/sql"
)

const createNewOrder = `-- name: CreateNewOrder :exec
INSERT INTO orders(bill_id, menu_id, amount, "type","size", menu_name)
SELECT ?,?,?,?,?,m.name FROM menu AS m
WHERE m.menu_id = ?
`

type CreateNewOrderParams struct {
	BillID   string
	MenuID   int64
	Amount   int64
	Type     sql.NullString
	Size     sql.NullString
	TargetID int64
}

func (q *Queries) CreateNewOrder(ctx context.Context, arg CreateNewOrderParams) error {
	_, err := q.db.ExecContext(ctx, createNewOrder,
		arg.BillID,
		arg.MenuID,
		arg.Amount,
		arg.Type,
		arg.Size,
		arg.TargetID,
	)
	return err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
`

func (q *Queries) DeleteOrder(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrder)
	return err
}

const getOrderFromBill = `-- name: GetOrderFromBill :many
SELECT order_id, o.bill_id,o.menu_name, o.menu_id, amount, o."size", o."type",1.0 * o.amount * (c.price + t.addition_price) AS total 
FROM orders AS o, category AS c, "type" AS t
WHERE o.bill_id = ? and c.menu_id = o.menu_id and t.menu_id = o.menu_id and c."size" = o."size" and t."type" = o."type"
`

type GetOrderFromBillRow struct {
	OrderID  int64
	BillID   string
	MenuName string
	MenuID   int64
	Amount   int64
	Size     sql.NullString
	Type     sql.NullString
	Total    int64
}

func (q *Queries) GetOrderFromBill(ctx context.Context, billID string) ([]GetOrderFromBillRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderFromBill, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderFromBillRow
	for rows.Next() {
		var i GetOrderFromBillRow
		if err := rows.Scan(
			&i.OrderID,
			&i.BillID,
			&i.MenuName,
			&i.MenuID,
			&i.Amount,
			&i.Size,
			&i.Type,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalByBillId = `-- name: GetTotalByBillId :one
SELECT sum(o.amount * (c.price + t.addition_price)) AS total
FROM orders AS o, category AS c, "type" AS t
WHERE bill_id = ? and c.menu_id = o.menu_id and t.menu_id = o.menu_id and c."size" = o."size" and t."type" = o."type"
`

func (q *Queries) GetTotalByBillId(ctx context.Context, billID string) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getTotalByBillId, billID)
	var total sql.NullFloat64
	err := row.Scan(&total)
	return total, err
}
