// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"
)

const createNewOrder = `-- name: CreateNewOrder :one
INSERT INTO "orders"(bill_id, menu_id, amount, menu_name)
SELECT ?,?,?, menu.name FROM menu
	WHERE menu.menu_id = ?
RETURNING order_id, bill_id, menu_id, amount, size, type
`

type CreateNewOrderParams struct {
	BillID       string
	MenuID       int64
	Amount       int64
	TargetMenuID int64
}

func (q *Queries) CreateNewOrder(ctx context.Context, arg CreateNewOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createNewOrder,
		arg.BillID,
		arg.MenuID,
		arg.Amount,
		arg.TargetMenuID,
	)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.BillID,
		&i.MenuID,
		&i.Amount,
		&i.Size,
		&i.Type,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM "orders"
`

func (q *Queries) DeleteOrder(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrder)
	return err
}

const getOrderFromBill = `-- name: GetOrderFromBill :many
SELECT order_id, bill_id, menu_id, amount, size, type FROM "orders" 
WHERE bill_id = ?
`

func (q *Queries) GetOrderFromBill(ctx context.Context, billID string) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrderFromBill, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.BillID,
			&i.MenuID,
			&i.Amount,
			&i.Size,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
