// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: type.sql

package database

import (
	"context"
	"database/sql"
)

const createType = `-- name: CreateType :exec
INSERT INTO "type"(menu_id, type, addition_price)
VALUES (?, ?, ?)
`

type CreateTypeParams struct {
	MenuID        int64
	Type          sql.NullString
	AdditionPrice float64
}

func (q *Queries) CreateType(ctx context.Context, arg CreateTypeParams) error {
	_, err := q.db.ExecContext(ctx, createType, arg.MenuID, arg.Type, arg.AdditionPrice)
	return err
}

const deleteAllType = `-- name: DeleteAllType :exec
delete from "type"
`

func (q *Queries) DeleteAllType(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllType)
	return err
}

const deleteTypeByMenuID = `-- name: DeleteTypeByMenuID :exec
delete from "type"
where menu_id = ?
`

func (q *Queries) DeleteTypeByMenuID(ctx context.Context, menuID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTypeByMenuID, menuID)
	return err
}

const getTypeByMenuID = `-- name: GetTypeByMenuID :many
select menu_id, type, addition_price from "type"
where menu_id = ?
`

func (q *Queries) GetTypeByMenuID(ctx context.Context, menuID int64) ([]Type, error) {
	rows, err := q.db.QueryContext(ctx, getTypeByMenuID, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Type
	for rows.Next() {
		var i Type
		if err := rows.Scan(&i.MenuID, &i.Type, &i.AdditionPrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
